spring:
  application:
    name: workload-service

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

server:
  servlet:
    context-path: /gym-crm/workload
  port: 8081

app:
  api:
    base-path: /api/v1
