spring:
  activemq:
    broker-url: ${ACTIVEMQ_BROKER_URL}
    user: ${ACTIVEMQ_USER}
    password: ${ACTIVEMQ_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URL}
  instance:
    prefer-ip-address: true

app:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
  jms:
    queues:
      trainer-workload: dev.trainer.workload.updates
      trainer-workload-dlq: dev.trainer.workload.updates.dlq
    concurrency: 1-5
    redelivery:
      initial-delay-ms: 1000
      maximum-redeliveries: 3
      maximum-delay-ms: 10000
      back-off-multiplier: 2.0
      use-exponential-back-off: true
