spring:
  application:
    name: workload-service
  profiles:
    active: local

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

server:
  servlet:
    context-path: /gym-crm/workload
  port: 8081

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true

app:
  api:
    base-path: /api/v1
  security:
    jwt:
      access-expiration-ms: 86400000
  jms:
    queues:
      trainer-workload: trainer.workload.updates
