spring:
  activemq:
    broker-url: failover:(tcp://localhost:61616)
    user: gym
    password: gym
  data:
    mongodb:
      host: localhost
      port: 27017
      database: gym_workload
      username: gym
      password: gym

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  jms:
    queues:
      trainer-workload: local.trainer.workload.updates
      trainer-workload-dlq: local.trainer.workload.updates.dlq
    concurrency: 1-5
    redelivery:
      initial-delay-ms: 1000
      maximum-redeliveries: 3
      maximum-delay-ms: 10000
      back-off-multiplier: 2.0
      use-exponential-back-off: true

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.gym.crm: DEBUG
