spring:
  activemq:
    broker-url: ${ACTIVEMQ_BROKER_URL}
    user: ${ACTIVEMQ_USER}
    password: ${ACTIVEMQ_PASSWORD}
  data:
    mongodb:
      uri: ${MONGO_URI}

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URL}
  instance:
    prefer-ip-address: true

app:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
  jms:
    queues:
      trainer-workload: ${JMS_QUEUE_TRAINER_WORKLOAD}
      trainer-workload-dlq: ${JMS_QUEUE_TRAINER_WORKLOAD_DLQ}
    concurrency: ${JMS_CONCURRENCY}
    redelivery:
      initial-delay-ms: ${JMS_REDELIVERY_INITIAL_DELAY_MS}
      maximum-redeliveries: ${JMS_REDELIVERY_MAXIMUM_REDELIVERIES}
      maximum-delay-ms: ${JMS_REDELIVERY_MAXIMUM_DELAY_MS}
      back-off-multiplier: ${JMS_REDELIVERY_BACK_OFF_MULTIPLIER}
      use-exponential-back-off: ${JMS_REDELIVERY_USE_EXPONENTIAL_BACK_OFF}
