spring:
  activemq:
    broker-url: ${ACTIVEMQ_BROKER_URL}
    user: ${ACTIVEMQ_USER}
    password: ${ACTIVEMQ_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URL}
  instance:
    prefer-ip-address: true

app:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
