spring:
  application:
    name: api-gateway
  profiles:
    active: local

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
