spring:
  application:
    name: discovery-server
  profiles:
    active: local

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetch-registry: false
