spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  data:
    redis:
      host: ${REDIS_HOST}
  activemq:
    broker-url: ${ACTIVEMQ_BROKER_URL}
    user: ${ACTIVEMQ_USER}
    password: ${ACTIVEMQ_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URL}
  instance:
    prefer-ip-address: true

app:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS}
  jms:
    queues:
      trainer-workload: ${JMS_QUEUE_TRAINER_WORKLOAD}

logging:
  level:
    root: WARN
    org.springframework: WARN
    com.gym.crm: INFO
