spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: ${REDIS_HOST}

app:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS}

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.gym.crm: DEBUG
